#!/usr/bin/env/bash
# cmds to install nginx and configures it on a remote server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Ngnix HTTP'

echo "Hello world!" | sudo tee /var/www/html/index.html

#testing nginx configuration
sudo nginx -t

sudo service reload nginx
